spring:
  profiles:
    active: prod
  mvc:
    throw-exception-if-no-handler-found: true
    # 请求超时时间
    async:
      request-timeout: 20000
  # 单个文件的最大值
  servlet:
    multipart:
      max-file-size: 50MB