server:
  port: 8800

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123qwe
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/pdf-opensea?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT

#rocketMQ
rocketmq:
  work: false
  #producer
  producer:
    groupName: chain-service-group
    namesrvAddr: 120.24.71.79:9876
    maxMessageSize: 4096
    sendMsgTimeout: 30000
    retryTimesWhenSendFailed: 3
  #consumer
  consumer:
    isOnOff: on
    namesrvAddr: 120.24.71.79:9876
    consumeThreadMin: 20
    consumeThreadMax: 64
    consumeMessageBatchMaxSize: 1
#rocketmq.name-server = 192.168.33.10:8080
#rocketmq.producer.group = chain-producer-group

encrype:
  key: dev-key

filePath:
  abi: contract/abi/
  bin: contract/bin/

bcos:
  config: classpath:fisco-config-test.xml
  groupId: 1
  encryptType: 0
  signType: 2